### ISSUE TITLE
Speaker social icon-links aren't initialized

### ISSUE THREAD

**Issue by piperchester** [gophercon/gc15#27]
Twitter, GitHub, and LinkedIn icon links are just redirecting to the same page:

![screen shot 2015-05-15 at 3 44 49 pm](https://cloud.githubusercontent.com/assets/1530684/7660588/66f6c320-fb19-11e4-80fa-430588f08faa.png)

**Comment by nathany** [comment]
I've come up with a fix for this (pretty easy), but still need to track down the URLs for the Twitter, GitHub and LinkedIn profiles of every speaker.
